Abort running a test script on fail on GA (#43)
`xargs` never fails unless a program finishes with an exit code 255.
See `man xargs`.

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -111,7 +111,8 @@ jobs:
 
       - name: Run test scripts
         shell: bash -e {0}
-        run: find content/blog/* -type d -exec bash -c 'cd "$0" && ./test_script.sh' {} \;
+        # `xargs` never fails unless a program finishes with an exit code 255. See `man xargs`.
+        run: find content/blog/* -type d -exec bash -c 'cd "$0" && ./test_script.sh || exit 255' {} \;
 
   deploy:
     runs-on: ubuntu-latest
